
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://aybygkwfqpsphhopatso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Ynlna3dmcXBzcGhob3BhdHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTQ3NjksImV4cCI6MjA3MDMzMDc2OX0.Nn6ifn3ii_fwjLMWeSGfD3SPns05ByYyanONYtfcEJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
